# 오류처리

### chapter 28.1 오류처리란

오류처리는 프로그램이 오류를 일으켰을 때 이것을 감지하고 회복시키는 과정.

-------------------------------------------------------------

### chapter 28.2 오류의 표현

스위프트에서 오류는 Error 라는 프로토콜을 준수하는 타입의 값을 통해 표현된다. Error 프로토콜은 사실상 요구사항이 없는 빈 프로토콜이지만, 오류를 표현하기 위한 타입(주로 열거형)은 이 프로토콜을 채택한다. 오류의 종류를 미리 예상한 다음, 오류 때문에 다음에 행할 동작이 정상적으로 진행되지 않을 때라면 오류를 던져 주면 된다. throw 구문. 만약 자금이 부족하고 동전이 5개 더 필요한 상황이라면 throw VendingMachineError.insufficientFunds(coinNeeded : 5)

-------------------------------------------------------------

### chapter 28.3 오류 포착 및 처리

오류를 던질 수도 있지만 오류가 던져지는 것에 대비하여 던져진 오류를 처리하기 위한 코드도 작성해야 한다. 예를 들어 던져진 오류가 무엇인지 판단하여 다시 문제를 해결한다든지, 다른 방법으로 문제 해결을 시도해 본다던지, 오류를 알리고 사용자에게 선택 권한을 넘겨주어 다음에 어떤 동작을 하게 할 것인지 결정하도록 유도하는 등의 코드를 작성해야 한다.

    함수에서 발생한 오류를 해당 함수를 호출한 코드에 알리는 방법
    do-catch 구문을 이용하여 오류를 처리하는 방법
    옵셔널 값으로 오류를 처리하는 방법
    오류가 발생하지 않을 것이라고 확신하는 방법
    
------------------------------------------------------------

### chapter 28.3.1 함수에서 발생한 오류 알리기

함수가 오류를 던지면 프로그램의 흐름이 바뀔 가능성이 매우 크다. 그러므로 어디서 오류를 던지고 받을 것인가 결정하는 것은 매우 중요하다. try 키워드로 던져진 오류를 받을 수 있다. try, try?, try! 등으로 표현이 가능하다.

    throws는 함수나 메서드의 자체 타입에도 영향을 미친다. 즉, throws 함수나 메서드는 같은 이름의 throws 가 명시되지 않는 함수나 메서드와 구분됩니다. 또, throws 를 포함한 함수, 메서드, 이니셜라이저는 일반 함수, 메서드, 이니셜라이저로 재정의를 할 수 없다. 반대로 일반 함수, 메서드, 이니셜라이저는 throws 함수, 메서드, 이니셜라이저로 재정의가 가능하다.
    
----------------------------------------------------

### chapter 28.3.3 옵셔널 값으로 오류처리

try? 를 사용하여 옵셔널 값으로 변환하여 오류를 처리할 수도 있다. try? 표현을 통해 동작하던 코드가 오류를 던지면 그 코드가 변환값이 nil 이 된다. try? 표현을 사용하여 호출한 함수가 오류를 던지면 반환 값이 nil 로 반환되고, 오류가 발생하지 않으몬 옵셔널 값으로 반환되는 것을 확인할 수 있다. do-catch 구문을 사용하지 않더라도 옵셔널을 사용하여 오류를 처리할 수도 있다. 

------------------------------------------------------------

### chapter 28.3.5 다시 던지기

함수나 메서드는 rethrows 키워드를 사용하여 자신의 매개변수로 전달받은 함수가 오류를 던진다는 것을 나타낼 수 있다. rethrows 키워드를 사용하여 다시 던지기가 가능하게 하려면 최소 하나 이상의 오류 발생 가능한 함수를 매개변수로 전달받아야 한다. 다시 던지기 함수 또는 메서드는 기본적으로 스스로 오류를 던지지 못한다. 자신 내부에 직접적으로 throw 구문을 사용할 수 없다. 그러나 catch 절 내부에서는 throw 구문을 작성할 수 있다. 다시 던지기 함수나 메서드가 오류를 던지는 함수 do-catch 구문 내부에서 호출하고 catch 절 내부에서 다른 오류를 던짐으로써 오류를 던지는 함수에서 발생한 오류를 제어할 수 있다. 다시 던지기 내부의 catch 절 내에서는 다시 던지기 함수의 매개변수로 전달받은 오류던지기 함수만 호출하고 결과로 다져진 오류만 제어할 수 있다.

-----------------------------------------------------------

### chapter 28.3.6 후처리 defer

defer 구문을 사용해 현재 코드 블록을 나가기 전에 꼭 실행해야 하는 코드를 작성해줄 수 있다. 즉 defer 구문은 코드가 블록을 어떤 식으로 빠져나가든 간에 꼭 실행해야 하는 마무리 작업을 할 수 있도록 도와준다. 오류가 발생해 코드 블록을 빠져나가거나, 정상적으로 코드가 블록을 빠져나가거나 defer 구문은 코드가 블록을 빠져 나가기전에 무조건 실행되는 것을 보장한다는 뜻이다. 예를 들어 함수 내에서 파일을 열어 사용하다가 오류가 발생하여 코드가 블록을 빠져나가더라도 파일을 정상적으로 닫아 메모리에서 해제해야 되기 때문에 defer 구문 내부에는 파일을 닫는 코드를 작성해주어 정상적으로 파일이 메모리에서 해제될 수 있도록 해야 된다.

    defer 구문과 오류 처리
    defer 구문은 오류처리 상황 뿐만 아니라 함수, 메서드, 반복문, 조건문 등등 보통의 코드 블록 어디에서든 사용할 수 있다. 만약 defer 구문이 없었더라면 중복된 코드가 많아지고, 유지관리가 어려워 지며 코드를 닫지 않는 실수를 할 가능성이 높아진다.
    
    
